#!/usr/bin/env bash
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

source "$script_dir/utils.sh"

if [[ -z "${DRY_RUN}" ]]; then
    DRY_RUN="1"
fi

export SCRIPTS_DIR=$script_dir
export SCRIPTS_DOWNLOAD_DIR="$script_dir/downloads"
export UTILS="$SCRIPTS_DIR/utils.sh"

if [ "$DRY_RUN" == "1" ]; then
    log "DOING DRY RUN" bold_yellow
fi

mkdir -p "$SCRIPTS_DOWNLOAD_DIR"

runs_dir="$(find "$script_dir"/scripts -mindepth 1 -maxdepth 1 -executable | sort)"
for s in $runs_dir; do
    log "[Running Script]: $s" bold_yellow

    if [[ $DRY_RUN == "0" ]]; then
        $s
    fi
    log "[Finished]: $s" bold_green
done

log "[Running Script]: Post Install" bold_yellow

"$script_dir"/postinstall

log "Done!" bold_green