#!/usr/bin/env bash

curl -Lo "$SCRIPTS_DOWNLOAD_DIR/FiraCode.zip"  https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/FiraCode.zip
curl -Lo "$SCRIPTS_DOWNLOAD_DIR/Iosevka.zip" "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/Iosevka.zip"

FONT_DIR="$HOME/.local/share/fonts"
mkdir -p "$FONT_DIR"

unzip -o "$SCRIPTS_DOWNLOAD_DIR/FiraCode.zip" -d "$FONT_DIR/FiraCode"
unzip -o "$SCRIPTS_DOWNLOAD_DIR/Iosevka.zip" -d "$FONT_DIR/Iosevka"

fc-cache -fv