#!/usr/bin/env bash

echo "code code/add-microsoft-repo boolean true" | sudo debconf-set-selections
wget -O "$SCRIPTS_DOWNLOAD_DIR/vscode.deb" "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64"
sudo apt -y install "$SCRIPTS_DOWNLOAD_DIR/vscode.deb"